export const mockReviews = [
  {
    id: 1,
    overallRating: 5,
    cleanlinessRating: 5,
    locationRating: 4,
    valueForMoneyRating: 5,
    communicationRating: 5,
    checkInRating: 5,
    reviewComment:
      "Homestay tuyệt vời! Chủ nhà thân thiện, phòng sạch sẽ và vị trí thuận tiện.",
    isVisible: true,
    isRecommended: true,
    helpfulCount: 12,
    hostResponse:
      "Cảm ơn bạn đã đánh giá! Rất vui khi bạn hài lòng với trải nghiệm.",
    hostRespondedAt: "2024-10-15T10:00:00Z",
    reviewerId: 1,
    reviewerName: "Nguyễn Văn A",
    reviewerAvatar: null,
    createdAt: "2024-10-10T08:30:00Z",
  },
  {
    id: 2,
    overallRating: 4,
    cleanlinessRating: 4,
    locationRating: 5,
    valueForMoneyRating: 4,
    communicationRating: 5,
    checkInRating: 4,
    reviewComment:
      "Vị trí đẹp, gần trung tâm. Phòng khá ổn, chỉ có điều hơi nhỏ.",
    isVisible: true,
    isRecommended: true,
    helpfulCount: 8,
    hostResponse: null,
    reviewerId: 2,
    reviewerName: "Trần Thị B",
    reviewerAvatar: null,
    createdAt: "2024-10-08T14:20:00Z",
  },
  {
    id: 3,
    overallRating: 5,
    cleanlinessRating: 5,
    locationRating: 5,
    valueForMoneyRating: 5,
    communicationRating: 5,
    checkInRating: 5,
    reviewComment: "Perfect! Sẽ quay lại lần sau.",
    isVisible: true,
    isRecommended: true,
    helpfulCount: 15,
    hostResponse: "Cảm ơn bạn! Chúng tôi rất mong được đón bạn trở lại!",
    hostRespondedAt: "2024-10-05T09:00:00Z",
    reviewerId: 3,
    reviewerName: "Lê Văn C",
    reviewerAvatar: null,
    createdAt: "2024-10-03T11:45:00Z",
  },
];

export const mockStats = {
  totalReviews: 48,
  averageOverallRating: 4.7,
  recommendationPercentage: 92,
  ratingDistribution: {
    5: 32,
    4: 10,
    3: 4,
    2: 1,
    1: 1,
  },
};
