export interface Province {
  name: string;
  nameWithoutAccent: string;
  country: string;
}

export const vietnamProvinces: Province[] = [
  { name: "Hà Nội", nameWithoutAccent: "Ha Noi", country: "Vietnam" },
  { name: "Hồ Chí Minh", nameWithoutAccent: "Ho Chi Minh", country: "Vietnam" },
  { name: "Đà Nẵng", nameWithoutAccent: "Da Nang", country: "Vietnam" },
  { name: "Hải Phòng", nameWithoutAccent: "Hai Phong", country: "Vietnam" },
  { name: "Cần Thơ", nameWithoutAccent: "Can Tho", country: "Vietnam" },

  // Miền Bắc
  { name: "An Giang", nameWithoutAccent: "An Giang", country: "Vietnam" },
  {
    name: "Bà Rịa - Vũng Tàu",
    nameWithoutAccent: "Ba Ria - Vung Tau",
    country: "Vietnam",
  },
  { name: "Bạc Liêu", nameWithoutAccent: "Bac Lieu", country: "Vietnam" },
  { name: "Bắc Giang", nameWithoutAccent: "Bac Giang", country: "Vietnam" },
  { name: "Bắc Kạn", nameWithoutAccent: "Bac Kan", country: "Vietnam" },
  { name: "Bắc Ninh", nameWithoutAccent: "Bac Ninh", country: "Vietnam" },
  { name: "Bến Tre", nameWithoutAccent: "Ben Tre", country: "Vietnam" },
  { name: "Bình Định", nameWithoutAccent: "Binh Dinh", country: "Vietnam" },
  { name: "Bình Dương", nameWithoutAccent: "Binh Duong", country: "Vietnam" },
  { name: "Bình Phước", nameWithoutAccent: "Binh Phuoc", country: "Vietnam" },
  { name: "Bình Thuận", nameWithoutAccent: "Binh Thuan", country: "Vietnam" },
  { name: "Cà Mau", nameWithoutAccent: "Ca Mau", country: "Vietnam" },
  { name: "Cao Bằng", nameWithoutAccent: "Cao Bang", country: "Vietnam" },
  { name: "Đắk Lắk", nameWithoutAccent: "Dak Lak", country: "Vietnam" },
  { name: "Đắk Nông", nameWithoutAccent: "Dak Nong", country: "Vietnam" },
  { name: "Điện Biên", nameWithoutAccent: "Dien Bien", country: "Vietnam" },
  { name: "Đồng Nai", nameWithoutAccent: "Dong Nai", country: "Vietnam" },
  { name: "Đồng Tháp", nameWithoutAccent: "Dong Thap", country: "Vietnam" },
  { name: "Gia Lai", nameWithoutAccent: "Gia Lai", country: "Vietnam" },
  { name: "Hà Giang", nameWithoutAccent: "Ha Giang", country: "Vietnam" },
  { name: "Hà Nam", nameWithoutAccent: "Ha Nam", country: "Vietnam" },
  { name: "Hà Tĩnh", nameWithoutAccent: "Ha Tinh", country: "Vietnam" },
  { name: "Hải Dương", nameWithoutAccent: "Hai Duong", country: "Vietnam" },
  { name: "Hậu Giang", nameWithoutAccent: "Hau Giang", country: "Vietnam" },
  { name: "Hòa Bình", nameWithoutAccent: "Hoa Binh", country: "Vietnam" },
  { name: "Hưng Yên", nameWithoutAccent: "Hung Yen", country: "Vietnam" },
  { name: "Khánh Hòa", nameWithoutAccent: "Khanh Hoa", country: "Vietnam" },
  { name: "Kiên Giang", nameWithoutAccent: "Kien Giang", country: "Vietnam" },
  { name: "Kon Tum", nameWithoutAccent: "Kon Tum", country: "Vietnam" },
  { name: "Lai Châu", nameWithoutAccent: "Lai Chau", country: "Vietnam" },
  { name: "Lâm Đồng", nameWithoutAccent: "Lam Dong", country: "Vietnam" },
  { name: "Lạng Sơn", nameWithoutAccent: "Lang Son", country: "Vietnam" },
  { name: "Lào Cai", nameWithoutAccent: "Lao Cai", country: "Vietnam" },
  { name: "Long An", nameWithoutAccent: "Long An", country: "Vietnam" },
  { name: "Nam Định", nameWithoutAccent: "Nam Dinh", country: "Vietnam" },
  { name: "Nghệ An", nameWithoutAccent: "Nghe An", country: "Vietnam" },
  { name: "Ninh Bình", nameWithoutAccent: "Ninh Binh", country: "Vietnam" },
  { name: "Ninh Thuận", nameWithoutAccent: "Ninh Thuan", country: "Vietnam" },
  { name: "Phú Thọ", nameWithoutAccent: "Phu Tho", country: "Vietnam" },
  { name: "Phú Yên", nameWithoutAccent: "Phu Yen", country: "Vietnam" },
  { name: "Quảng Bình", nameWithoutAccent: "Quang Binh", country: "Vietnam" },
  { name: "Quảng Nam", nameWithoutAccent: "Quang Nam", country: "Vietnam" },
  { name: "Quảng Ngãi", nameWithoutAccent: "Quang Ngai", country: "Vietnam" },
  { name: "Quảng Ninh", nameWithoutAccent: "Quang Ninh", country: "Vietnam" },
  { name: "Quảng Trị", nameWithoutAccent: "Quang Tri", country: "Vietnam" },
  { name: "Sóc Trăng", nameWithoutAccent: "Soc Trang", country: "Vietnam" },
  { name: "Sơn La", nameWithoutAccent: "Son La", country: "Vietnam" },
  { name: "Tây Ninh", nameWithoutAccent: "Tay Ninh", country: "Vietnam" },
  { name: "Thái Bình", nameWithoutAccent: "Thai Binh", country: "Vietnam" },
  { name: "Thái Nguyên", nameWithoutAccent: "Thai Nguyen", country: "Vietnam" },
  { name: "Thanh Hóa", nameWithoutAccent: "Thanh Hoa", country: "Vietnam" },
  {
    name: "Thừa Thiên Huế",
    nameWithoutAccent: "Thua Thien Hue",
    country: "Vietnam",
  },
  { name: "Tiền Giang", nameWithoutAccent: "Tien Giang", country: "Vietnam" },
  { name: "Trà Vinh", nameWithoutAccent: "Tra Vinh", country: "Vietnam" },
  { name: "Tuyên Quang", nameWithoutAccent: "Tuyen Quang", country: "Vietnam" },
  { name: "Vĩnh Long", nameWithoutAccent: "Vinh Long", country: "Vietnam" },
  { name: "Vĩnh Phúc", nameWithoutAccent: "Vinh Phuc", country: "Vietnam" },
  { name: "Yên Bái", nameWithoutAccent: "Yen Bai", country: "Vietnam" },
  {
    name: "Vịnh Hạ Long",
    nameWithoutAccent: "Vinh Ha Long",
    country: "Vietnam",
  },
  { name: "Vịnh Lan Hạ", nameWithoutAccent: "Vinh Lan Ha", country: "Vietnam" },
  { name: "Đảo Cát Bà", nameWithoutAccent: "Dao Cat Ba", country: "Vietnam" },
  { name: "Hội An", nameWithoutAccent: "Hoi An", country: "Vietnam" },
  {
    name: "Phố Cổ Hội An",
    nameWithoutAccent: "Pho Co Hoi An",
    country: "Vietnam",
  },
  { name: "Phong Nha", nameWithoutAccent: "Phong Nha", country: "Vietnam" },
  {
    name: "Hang Sơn Đoòng",
    nameWithoutAccent: "Hang Son Doong",
    country: "Vietnam",
  },
  {
    name: "Vườn Quốc Gia Phong Nha - Kẻ Bàng",
    nameWithoutAccent: "Vuon Quoc Gia Phong Nha - Ke Bang",
    country: "Vietnam",
  },
  { name: "Sapa", nameWithoutAccent: "Sapa", country: "Vietnam" },
  {
    name: "Thung Lũng Mường Hoa",
    nameWithoutAccent: "Thung Lung Muong Hoa",
    country: "Vietnam",
  },
  {
    name: "Làng Cát Cát",
    nameWithoutAccent: "Lang Cat Cat",
    country: "Vietnam",
  },
  { name: "Làng Tả Van", nameWithoutAccent: "Lang Ta Van", country: "Vietnam" },
  { name: "Ninh Bình", nameWithoutAccent: "Ninh Binh", country: "Vietnam" },
  { name: "Tràng An", nameWithoutAccent: "Trang An", country: "Vietnam" },
  {
    name: "Tam Cốc - Bích Động",
    nameWithoutAccent: "Tam Coc - Bich Dong",
    country: "Vietnam",
  },
  { name: "Hang Múa", nameWithoutAccent: "Hang Mua", country: "Vietnam" },
  { name: "Phú Quốc", nameWithoutAccent: "Phu Quoc", country: "Vietnam" },
  {
    name: "Bãi Sao Phú Quốc",
    nameWithoutAccent: "Bai Sao Phu Quoc",
    country: "Vietnam",
  },
  {
    name: "Bãi Dài Phú Quốc",
    nameWithoutAccent: "Bai Dai Phu Quoc",
    country: "Vietnam",
  },
  { name: "Mũi Né", nameWithoutAccent: "Mui Ne", country: "Vietnam" },
  {
    name: "Đồi Cát Mũi Né",
    nameWithoutAccent: "Doi Cat Mui Ne",
    country: "Vietnam",
  },
  { name: "Hòn Rơm", nameWithoutAccent: "Hon Rom", country: "Vietnam" },
  { name: "Quy Nhơn", nameWithoutAccent: "Quy Nhon", country: "Vietnam" },
  { name: "Bãi Kỳ Co", nameWithoutAccent: "Bai Ky Co", country: "Vietnam" },
  { name: "Eo Gió", nameWithoutAccent: "Eo Gio", country: "Vietnam" },
  { name: "Phan Thiết", nameWithoutAccent: "Phan Thiet", country: "Vietnam" },
  { name: "Bãi Rạng", nameWithoutAccent: "Bai Rang", country: "Vietnam" },
  { name: "Huế", nameWithoutAccent: "Hue", country: "Vietnam" },
  {
    name: "Kinh Thành Huế",
    nameWithoutAccent: "Kinh Thanh Hue",
    country: "Vietnam",
  },
  { name: "Lăng Tự Đức", nameWithoutAccent: "Lang Tu Duc", country: "Vietnam" },
  { name: "Đại Nội Huế", nameWithoutAccent: "Dai Noi Hue", country: "Vietnam" },
  { name: "Mai Châu", nameWithoutAccent: "Mai Chau", country: "Vietnam" },
  {
    name: "Thung Lũng Mai Châu",
    nameWithoutAccent: "Thung Lung Mai Chau",
    country: "Vietnam",
  },
  { name: "Pù Luông", nameWithoutAccent: "Pu Luong", country: "Vietnam" },
  { name: "Bản Hiêu", nameWithoutAccent: "Ban Hieu", country: "Vietnam" },
  { name: "Bản Đôn", nameWithoutAccent: "Ban Don", country: "Vietnam" },
  { name: "Bà Nà Hills", nameWithoutAccent: "Ba Na Hills", country: "Vietnam" },
  { name: "Cầu Vàng", nameWithoutAccent: "Cau Vang", country: "Vietnam" },
  { name: "Mỹ Khê", nameWithoutAccent: "My Khe", country: "Vietnam" },
  {
    name: "Bán Đảo Sơn Trà",
    nameWithoutAccent: "Ban Dao Son Tra",
    country: "Vietnam",
  },
  { name: "Bãi Đá Đen", nameWithoutAccent: "Bai Da Den", country: "Vietnam" },
  { name: "Hà Giang", nameWithoutAccent: "Ha Giang", country: "Vietnam" },
  {
    name: "Đèo Mã Pí Lèng",
    nameWithoutAccent: "Deo Ma Pi Leng",
    country: "Vietnam",
  },
  {
    name: "Cột Cờ Lũng Cú",
    nameWithoutAccent: "Cot Co Lung Cu",
    country: "Vietnam",
  },
  { name: "Đồng Văn", nameWithoutAccent: "Dong Van", country: "Vietnam" },
  { name: "Mèo Vạc", nameWithoutAccent: "Meo Vac", country: "Vietnam" },
  { name: "Ba Bể", nameWithoutAccent: "Ba Be", country: "Vietnam" },
  { name: "Hồ Ba Bể", nameWithoutAccent: "Ho Ba Be", country: "Vietnam" },
  {
    name: "Vườn Quốc Gia Ba Bể",
    nameWithoutAccent: "Vuon Quoc Gia Ba Be",
    country: "Vietnam",
  },
  { name: "Côn Đảo", nameWithoutAccent: "Con Dao", country: "Vietnam" },
  {
    name: "Bãi Đầm Trầu",
    nameWithoutAccent: "Bai Dam Trầu",
    country: "Vietnam",
  },
  { name: "Hòn Tằm", nameWithoutAccent: "Hon Tam", country: "Vietnam" },
  {
    name: "Bãi Trước Nha Trang",
    nameWithoutAccent: "Bai Truoc Nha Trang",
    country: "Vietnam",
  },
  {
    name: "Vinpearl Land Nha Trang",
    nameWithoutAccent: "Vinpearl Land Nha Trang",
    country: "Vietnam",
  },
  {
    name: "Thác Datanla",
    nameWithoutAccent: "Thac Datanla",
    country: "Vietnam",
  },
  {
    name: "Thác Pongour",
    nameWithoutAccent: "Thac Pongour",
    country: "Vietnam",
  },
  {
    name: "Hồ Xuân Hương",
    nameWithoutAccent: "Ho Xuan Huong",
    country: "Vietnam",
  },
  {
    name: "Chợ Đêm Đà Lạt",
    nameWithoutAccent: "Cho Dem Da Lat",
    country: "Vietnam",
  },
  {
    name: "Mekong Delta",
    nameWithoutAccent: "Mekong Delta",
    country: "Vietnam",
  },
  { name: "Cái Bè", nameWithoutAccent: "Cai Be", country: "Vietnam" },
  { name: "Mỹ Tho", nameWithoutAccent: "My Tho", country: "Vietnam" },
  { name: "Bến Tre", nameWithoutAccent: "Ben Tre", country: "Vietnam" },
  { name: "Vàm Xáng", nameWithoutAccent: "Vam Xang", country: "Vietnam" },
  {
    name: "Doc Let Beach",
    nameWithoutAccent: "Doc Let Beach",
    country: "Vietnam",
  },
  {
    name: "Jungle Beach",
    nameWithoutAccent: "Jungle Beach",
    country: "Vietnam",
  },
  { name: "Mường Lống", nameWithoutAccent: "Muong Long", country: "Vietnam" },
  { name: "Pac Ngoi", nameWithoutAccent: "Pac Ngoi", country: "Vietnam" },
  { name: "Chợ Đồn", nameWithoutAccent: "Cho Don", country: "Vietnam" },
  { name: "Quảng Bá", nameWithoutAccent: "Quang Ba", country: "Vietnam" },
  { name: "Yên Minh", nameWithoutAccent: "Yen Minh", country: "Vietnam" },
  { name: "Quản Bạ", nameWithoutAccent: "Quan Ba", country: "Vietnam" },
  { name: "Tam Đảo", nameWithoutAccent: "Tam Dao", country: "Vietnam" },
  { name: "Bãi Lữ", nameWithoutAccent: "Bai Lu", country: "Vietnam" },
  { name: "Cù Lao Chàm", nameWithoutAccent: "Cu Lao Cham", country: "Vietnam" },
  {
    name: "Bán Đảo Cam Ranh",
    nameWithoutAccent: "Ban Dao Cam Ranh",
    country: "Vietnam",
  },
  {
    name: "Côn Sơn - Kiếp Bạc",
    nameWithoutAccent: "Con Son - Kiep Bac",
    country: "Vietnam",
  },
  {
    name: "Chùa Bái Đính",
    nameWithoutAccent: "Chua Bai Dinh",
    country: "Vietnam",
  },
  {
    name: "Cố Đô Hoa Lư",
    nameWithoutAccent: "Co Do Hoa Lu",
    country: "Vietnam",
  },
  { name: "Chùa Hương", nameWithoutAccent: "Chua Huong", country: "Vietnam" },
  { name: "Yên Tử", nameWithoutAccent: "Yen Tu", country: "Vietnam" },
  {
    name: "Chùa Một Cột",
    nameWithoutAccent: "Chua Mot Cot",
    country: "Vietnam",
  },
  {
    name: "Văn Miếu Quốc Tử Giám",
    nameWithoutAccent: "Van Mieu Quoc Tu Giam",
    country: "Vietnam",
  },
  {
    name: "Hồ Hoàn Kiếm",
    nameWithoutAccent: "Ho Hoan Kiem",
    country: "Vietnam",
  },
  {
    name: "Phố Cổ Hà Nội",
    nameWithoutAccent: "Pho Co Ha Noi",
    country: "Vietnam",
  },
  {
    name: "Làng Gốm Bát Tràng",
    nameWithoutAccent: "Lang Gom Bat Trang",
    country: "Vietnam",
  },
  {
    name: "Làng Lụa Vạn Phúc",
    nameWithoutAccent: "Lang Lua Van Phuc",
    country: "Vietnam",
  },
  { name: "Đảo Cô Tô", nameWithoutAccent: "Dao Co To", country: "Vietnam" },
  {
    name: "Đảo Quan Lạn",
    nameWithoutAccent: "Dao Quan Lan",
    country: "Vietnam",
  },
  {
    name: "Đảo Minh Châu",
    nameWithoutAccent: "Dao Minh Chau",
    country: "Vietnam",
  },
  {
    name: "Đảo Ngọc Vừng",
    nameWithoutAccent: "Dao Ngoc Vung",
    country: "Vietnam",
  },
  { name: "Đảo Lý Sơn", nameWithoutAccent: "Dao Ly Son", country: "Vietnam" },
  {
    name: "Núi Thần Tài",
    nameWithoutAccent: "Nui Than Tai",
    country: "Vietnam",
  },
  {
    name: "Suối Khoáng Nóng Núi Thần Tài",
    nameWithoutAccent: "Suoi Khoang Nong Nui Than Tai",
    country: "Vietnam",
  },
  {
    name: "Suối Tiên Đà Nẵng",
    nameWithoutAccent: "Suoi Tien Da Nang",
    country: "Vietnam",
  },
  {
    name: "Công Viên Châu Á",
    nameWithoutAccent: "Cong Vien Chau A",
    country: "Vietnam",
  },
  {
    name: "VinWonders Nam Hội An",
    nameWithoutAccent: "VinWonders Nam Hoi An",
    country: "Vietnam",
  },
  {
    name: "Rừng Dừa Bảy Mẫu",
    nameWithoutAccent: "Rung Dua Bay Mau",
    country: "Vietnam",
  },
  {
    name: "Làng Rau Trà Quế",
    nameWithoutAccent: "Lang Rau Tra Que",
    country: "Vietnam",
  },
  {
    name: "Làng Mộc Kim Bồng",
    nameWithoutAccent: "Lang Moc Kim Bong",
    country: "Vietnam",
  },
  {
    name: "Làng Gốm Thanh Hà",
    nameWithoutAccent: "Lang Gom Thanh Ha",
    country: "Vietnam",
  },
  {
    name: "Đồi Chè Trái Tim",
    nameWithoutAccent: "Doi Che Trai Tim",
    country: "Vietnam",
  },
  {
    name: "Thung Lũng Tình Yêu",
    nameWithoutAccent: "Thung Lung Tinh Yeu",
    country: "Vietnam",
  },
  {
    name: "Hồ Tuyền Lâm",
    nameWithoutAccent: "Ho Tuyen Lam",
    country: "Vietnam",
  },
  {
    name: "Thiền Viện Trúc Lâm",
    nameWithoutAccent: "Thien Vien Truc Lam",
    country: "Vietnam",
  },
  { name: "Ga Đà Lạt", nameWithoutAccent: "Ga Da Lat", country: "Vietnam" },
  {
    name: "Nhà Thờ Domain De Marie",
    nameWithoutAccent: "Nha Tho Domain De Marie",
    country: "Vietnam",
  },
  {
    name: "Cánh Đồng Hoa Đà Lạt",
    nameWithoutAccent: "Canh Dong Hoa Da Lat",
    country: "Vietnam",
  },
  {
    name: "Đồi Chè Cầu Đất",
    nameWithoutAccent: "Doi Che Cau Dat",
    country: "Vietnam",
  },
  { name: "Thác Prenn", nameWithoutAccent: "Thac Prenn", country: "Vietnam" },
  { name: "Thác Voi", nameWithoutAccent: "Thac Voi", country: "Vietnam" },
  { name: "Thác Cam Ly", nameWithoutAccent: "Thac Cam Ly", country: "Vietnam" },
  { name: "Hồ Vô Cực", nameWithoutAccent: "Ho Vo Cuc", country: "Vietnam" },
  {
    name: "Cầu Tình Đà Lạt",
    nameWithoutAccent: "Cau Tinh Da Lat",
    country: "Vietnam",
  },
  { name: "Làng Cù Lần", nameWithoutAccent: "Lang Cu Lan", country: "Vietnam" },
  {
    name: "Khu Du Lịch Madagui",
    nameWithoutAccent: "Khu Du Lich Madagui",
    country: "Vietnam",
  },
  { name: "Suối Mơ", nameWithoutAccent: "Suoi Mo", country: "Vietnam" },
  { name: "Đảo Bình Ba", nameWithoutAccent: "Dao Binh Ba", country: "Vietnam" },
  {
    name: "Đảo Bình Hưng",
    nameWithoutAccent: "Dao Binh Hung",
    country: "Vietnam",
  },
  {
    name: "Đảo Điệp Sơn",
    nameWithoutAccent: "Dao Diep Son",
    country: "Vietnam",
  },
  {
    name: "Đảo Robinson",
    nameWithoutAccent: "Dao Robinson",
    country: "Vietnam",
  },
  { name: "Hòn Nội", nameWithoutAccent: "Hon Noi", country: "Vietnam" },
  { name: "Hòn Mun", nameWithoutAccent: "Hon Mun", country: "Vietnam" },
  { name: "Hòn Tằm", nameWithoutAccent: "Hon Tam", country: "Vietnam" },
  { name: "Hòn Chồng", nameWithoutAccent: "Hon Chong", country: "Vietnam" },
  {
    name: "Tháp Bà Ponagar",
    nameWithoutAccent: "Thap Ba Ponagar",
    country: "Vietnam",
  },
  {
    name: "Viện Hải Dương Học",
    nameWithoutAccent: "Vien Hai Duong Hoc",
    country: "Vietnam",
  },
  {
    name: "Bãi Dài Nha Trang",
    nameWithoutAccent: "Bai Dai Nha Trang",
    country: "Vietnam",
  },
  { name: "Bãi Dương", nameWithoutAccent: "Bai Duong", country: "Vietnam" },
  { name: "Bãi Trũ", nameWithoutAccent: "Bai Tru", country: "Vietnam" },
  { name: "Bãi Bàng", nameWithoutAccent: "Bai Bang", country: "Vietnam" },
  {
    name: "Đồng Cừu Suối Tiên",
    nameWithoutAccent: "Dong Cuu Suoi Tien",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cổ Cái Bầu",
    nameWithoutAccent: "Lang Chai Co Cai Bau",
    country: "Vietnam",
  },
  { name: "Đảo Trần", nameWithoutAccent: "Dao Tran", country: "Vietnam" },
  {
    name: "Đảo Tuần Châu",
    nameWithoutAccent: "Dao Tuan Chau",
    country: "Vietnam",
  },
  { name: "Đảo Reu", nameWithoutAccent: "Dao Reu", country: "Vietnam" },
  {
    name: "Vườn Quốc Gia Cát Tiên",
    nameWithoutAccent: "Vuon Quoc Gia Cat Tien",
    country: "Vietnam",
  },
  { name: "Bàu Sấu", nameWithoutAccent: "Bau Sau", country: "Vietnam" },
  { name: "Thác Buôn", nameWithoutAccent: "Thac Buon", country: "Vietnam" },
  { name: "Hồ Lắk", nameWithoutAccent: "Ho Lak", country: "Vietnam" },
  {
    name: "Biệt Điện Bảo Đại",
    nameWithoutAccent: "Biet Dien Bao Dai",
    country: "Vietnam",
  },
  {
    name: "Dinh Thượng Đà Lạt",
    nameWithoutAccent: "Dinh Thuong Da Lat",
    country: "Vietnam",
  },
  {
    name: "Nhà Ga Đà Lạt",
    nameWithoutAccent: "Nha Ga Da Lat",
    country: "Vietnam",
  },
  { name: "Chợ Đà Lạt", nameWithoutAccent: "Cho Da Lat", country: "Vietnam" },
  {
    name: "Làng Hoa Vạn Thành",
    nameWithoutAccent: "Lang Hoa Van Thanh",
    country: "Vietnam",
  },
  {
    name: "Làng Hoa Thái Phiên",
    nameWithoutAccent: "Lang Hoa Thai Phien",
    country: "Vietnam",
  },
  { name: "Đồi Mộng Mơ", nameWithoutAccent: "Doi Mong Mo", country: "Vietnam" },
  {
    name: "Thung Lũng Vàng",
    nameWithoutAccent: "Thung Lung Vang",
    country: "Vietnam",
  },
  {
    name: "Hồ Suối Vàng",
    nameWithoutAccent: "Ho Suoi Vang",
    country: "Vietnam",
  },
  {
    name: "Cây Thông Cô Đơn",
    nameWithoutAccent: "Cay Thong Co Don",
    country: "Vietnam",
  },
  {
    name: "Núi Langbiang",
    nameWithoutAccent: "Nui Langbiang",
    country: "Vietnam",
  },
  {
    name: "Làng Dân Tộc K’Ho",
    nameWithoutAccent: "Lang Dan Toc K'Ho",
    country: "Vietnam",
  },
  {
    name: "Thác Liêng Nung",
    nameWithoutAccent: "Thac Lieng Nung",
    country: "Vietnam",
  },
  { name: "Thác Đambri", nameWithoutAccent: "Thac Dambri", country: "Vietnam" },
  {
    name: "Thác Jráiblian",
    nameWithoutAccent: "Thac Jraiblian",
    country: "Vietnam",
  },
  { name: "Hồ Ankroet", nameWithoutAccent: "Ho Ankroet", country: "Vietnam" },
  {
    name: "Thiền Viện Vạn Hạnh",
    nameWithoutAccent: "Thien Vien Van Hanh",
    country: "Vietnam",
  },
  {
    name: "Chùa Linh Phước",
    nameWithoutAccent: "Chua Linh Phuoc",
    country: "Vietnam",
  },
  {
    name: "Chùa Ve Chai",
    nameWithoutAccent: "Chua Ve Chai",
    country: "Vietnam",
  },
  { name: "Đèo Prenn", nameWithoutAccent: "Deo Prenn", country: "Vietnam" },
  {
    name: "Đèo Ngoạn Mục",
    nameWithoutAccent: "Deo Ngoan Muc",
    country: "Vietnam",
  },
  { name: "Đèo Dran", nameWithoutAccent: "Deo Dran", country: "Vietnam" },
  { name: "Đèo Bảo Lộc", nameWithoutAccent: "Deo Bao Loc", country: "Vietnam" },
  {
    name: "Vườn Quốc Gia Bidoup - Núi Bà",
    nameWithoutAccent: "Vuon Quoc Gia Bidoup - Nui Ba",
    country: "Vietnam",
  },
  {
    name: "Hồ Dankia - Suối Vàng",
    nameWithoutAccent: "Ho Dankia - Suoi Vang",
    country: "Vietnam",
  },
  {
    name: "Thác Hang Cọp",
    nameWithoutAccent: "Thac Hang Cop",
    country: "Vietnam",
  },
  { name: "Thác Bobla", nameWithoutAccent: "Thac Bobla", country: "Vietnam" },
  { name: "Làng Cù Lần", nameWithoutAccent: "Lang Cu Lan", country: "Vietnam" },
  {
    name: "Khu Du Lịch Lá Phong",
    nameWithoutAccent: "Khu Du Lich La Phong",
    country: "Vietnam",
  },
  {
    name: "Cánh Đồng Hoa Hướng Dương",
    nameWithoutAccent: "Canh Dong Hoa Huong Duong",
    country: "Vietnam",
  },
  {
    name: "Cánh Đồng Hoa Cẩm Tú Cầu",
    nameWithoutAccent: "Canh Dong Hoa Cam Tu Cau",
    country: "Vietnam",
  },
  {
    name: "Cánh Đồng Hoa Tam Giác Mạch",
    nameWithoutAccent: "Canh Dong Hoa Tam Giac Mach",
    country: "Vietnam",
  },
  {
    name: "Làng Tre Việt",
    nameWithoutAccent: "Lang Tre Viet",
    country: "Vietnam",
  },
  {
    name: "Làng Bích Họa Tam Thanh",
    nameWithoutAccent: "Lang Bich Hoa Tam Thanh",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Xóm Rớ",
    nameWithoutAccent: "Lang Chai Xom Ro",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Mũi Né",
    nameWithoutAccent: "Lang Chai Mui Ne",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Bích Đầm",
    nameWithoutAccent: "Lang Chai Bich Dam",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cửa Đại",
    nameWithoutAccent: "Lang Chai Cua Dai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cửa Vạn",
    nameWithoutAccent: "Lang Chai Cua Van",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Ba Hang",
    nameWithoutAccent: "Lang Chai Ba Hang",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cửa Bé",
    nameWithoutAccent: "Lang Chai Cua Be",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Lăng Cô",
    nameWithoutAccent: "Lang Chai Lang Co",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Nhơn Hải",
    nameWithoutAccent: "Lang Chai Nhon Hai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Vĩnh Lương",
    nameWithoutAccent: "Lang Chai Vinh Luong",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Vĩnh Hy",
    nameWithoutAccent: "Lang Chai Vinh Hy",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cầu Đá",
    nameWithoutAccent: "Lang Chai Cau Da",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Yến",
    nameWithoutAccent: "Lang Chai Hon Yen",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Phước Hải",
    nameWithoutAccent: "Lang Chai Phuoc Hai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Long Hải",
    nameWithoutAccent: "Lang Chai Long Hai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Lộc An",
    nameWithoutAccent: "Lang Chai Loc An",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hồ Tràm",
    nameWithoutAccent: "Lang Chai Ho Tram",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hồ Cốc",
    nameWithoutAccent: "Lang Chai Ho Coc",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Bình Châu",
    nameWithoutAccent: "Lang Chai Binh Chau",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Xuyên Mộc",
    nameWithoutAccent: "Lang Chai Xuyen Moc",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Đầm Thị Nại",
    nameWithoutAccent: "Lang Chai Dam Thi Nai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Gành Đỏ",
    nameWithoutAccent: "Lang Chai Ganh Do",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Gành Hào",
    nameWithoutAccent: "Lang Chai Ganh Hao",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cà Ná",
    nameWithoutAccent: "Lang Chai Ca Na",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cổ Thạch",
    nameWithoutAccent: "Lang Chai Co Thach",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Mũi Dinh",
    nameWithoutAccent: "Lang Chai Mui Dinh",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Ninh Chữ",
    nameWithoutAccent: "Lang Chai Ninh Chu",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Vĩnh Hải",
    nameWithoutAccent: "Lang Chai Vinh Hai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Đông Hải",
    nameWithoutAccent: "Lang Chai Dong Hai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài An Thới",
    nameWithoutAccent: "Lang Chai An Thoi",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Rạch Vẹm",
    nameWithoutAccent: "Lang Chai Rach Vem",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hàm Ninh",
    nameWithoutAccent: "Lang Chai Ham Ninh",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cửa Cạn",
    nameWithoutAccent: "Lang Chai Cua Can",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Bãi Thơm",
    nameWithoutAccent: "Lang Chai Bai Thom",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Dương Đông",
    nameWithoutAccent: "Lang Chai Duong Dong",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Gành Dầu",
    nameWithoutAccent: "Lang Chai Ganh Dau",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Cửa Lấp",
    nameWithoutAccent: "Lang Chai Cua Lap",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Ông Lang",
    nameWithoutAccent: "Lang Chai Ong Lang",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Rạch Giá",
    nameWithoutAccent: "Lang Chai Rach Gia",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đất",
    nameWithoutAccent: "Lang Chai Hon Dat",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Nghệ",
    nameWithoutAccent: "Lang Chai Hon Nghe",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Sơn",
    nameWithoutAccent: "Lang Chai Hon Son",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Nam Du",
    nameWithoutAccent: "Lang Chai Nam Du",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Tre",
    nameWithoutAccent: "Lang Chai Hon Tre",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Heo",
    nameWithoutAccent: "Lang Chai Hon Heo",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Khoai",
    nameWithoutAccent: "Lang Chai Hon Khoai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Chuối",
    nameWithoutAccent: "Lang Chai Hon Chuoi",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Nưa",
    nameWithoutAccent: "Lang Chai Hon Nua",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Yến",
    nameWithoutAccent: "Lang Chai Hon Yen",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Móng Tay",
    nameWithoutAccent: "Lang Chai Hon Mong Tay",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Gầm Ghì",
    nameWithoutAccent: "Lang Chai Hon Gam Ghi",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Mây Rút",
    nameWithoutAccent: "Lang Chai Hon May Rut",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Thơm",
    nameWithoutAccent: "Lang Chai Hon Thom",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Một",
    nameWithoutAccent: "Lang Chai Hon Mot",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Bồ",
    nameWithoutAccent: "Lang Chai Hon Bo",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đỏ",
    nameWithoutAccent: "Lang Chai Hon Do",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Ông",
    nameWithoutAccent: "Lang Chai Hon Ong",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Dứa",
    nameWithoutAccent: "Lang Chai Hon Dua",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Rái",
    nameWithoutAccent: "Lang Chai Hon Rai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Chùa",
    nameWithoutAccent: "Lang Chai Hon Chua",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Lớn",
    nameWithoutAccent: "Lang Chai Hon Lon",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Nhàn",
    nameWithoutAccent: "Lang Chai Hon Nhan",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Ngang",
    nameWithoutAccent: "Lang Chai Hon Ngang",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Tai",
    nameWithoutAccent: "Lang Chai Hon Tai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Trứng",
    nameWithoutAccent: "Lang Chai Hon Trung",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đá Bạc",
    nameWithoutAccent: "Lang Chai Hon Da Bac",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Phụ Tử",
    nameWithoutAccent: "Lang Chai Hon Phu Tu",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đất",
    nameWithoutAccent: "Lang Chai Hon Dat",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Me",
    nameWithoutAccent: "Lang Chai Hon Me",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Nghệ",
    nameWithoutAccent: "Lang Chai Hon Nghe",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Sơn",
    nameWithoutAccent: "Lang Chai Hon Son",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đốc",
    nameWithoutAccent: "Lang Chai Hon Doc",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Chông",
    nameWithoutAccent: "Lang Chai Hon Chong",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Rùa",
    nameWithoutAccent: "Lang Chai Hon Rua",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Bà",
    nameWithoutAccent: "Lang Chai Hon Ba",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Lân",
    nameWithoutAccent: "Lang Chai Hon Lan",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Củ Tron",
    nameWithoutAccent: "Lang Chai Hon Cu Tron",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Móng Tay",
    nameWithoutAccent: "Lang Chai Hon Mong Tay",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Gầm Ghì",
    nameWithoutAccent: "Lang Chai Hon Gam Ghi",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Mây Rút",
    nameWithoutAccent: "Lang Chai Hon May Rut",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Thơm",
    nameWithoutAccent: "Lang Chai Hon Thom",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Một",
    nameWithoutAccent: "Lang Chai Hon Mot",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Bồ",
    nameWithoutAccent: "Lang Chai Hon Bo",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đỏ",
    nameWithoutAccent: "Lang Chai Hon Do",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Ông",
    nameWithoutAccent: "Lang Chai Hon Ong",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Dứa",
    nameWithoutAccent: "Lang Chai Hon Dua",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Rái",
    nameWithoutAccent: "Lang Chai Hon Rai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Chùa",
    nameWithoutAccent: "Lang Chai Hon Chua",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Lớn",
    nameWithoutAccent: "Lang Chai Hon Lon",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Nhàn",
    nameWithoutAccent: "Lang Chai Hon Nhan",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Ngang",
    nameWithoutAccent: "Lang Chai Hon Ngang",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Tai",
    nameWithoutAccent: "Lang Chai Hon Tai",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Trứng",
    nameWithoutAccent: "Lang Chai Hon Trung",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đá Bạc",
    nameWithoutAccent: "Lang Chai Hon Da Bac",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Phụ Tử",
    nameWithoutAccent: "Lang Chai Hon Phu Tu",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đất",
    nameWithoutAccent: "Lang Chai Hon Dat",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Me",
    nameWithoutAccent: "Lang Chai Hon Me",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Nghệ",
    nameWithoutAccent: "Lang Chai Hon Nghe",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Sơn",
    nameWithoutAccent: "Lang Chai Hon Son",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Đốc",
    nameWithoutAccent: "Lang Chai Hon Doc",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Chông",
    nameWithoutAccent: "Lang Chai Hon Chong",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Rùa",
    nameWithoutAccent: "Lang Chai Hon Rua",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Bà",
    nameWithoutAccent: "Lang Chai Hon Ba",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Lân",
    nameWithoutAccent: "Lang Chai Hon Lan",
    country: "Vietnam",
  },
  {
    name: "Làng Chài Hòn Củ Tron",
    nameWithoutAccent: "Lang Chai Hon Cu Tron",
    country: "Vietnam",
  },
];
